/**
 * LocalFonts.tsx — Load pre-downloaded Google Fonts from public/fonts/
 *
 * Replaces @remotion/google-fonts runtime downloads with local FontFace loading.
 * Fonts are served from the project's public/fonts/ directory via Remotion's staticFile().
 *
 * Usage in Root.tsx:
 *   import { loadLocalFont } from "./components/LocalFonts";
 *   const notoSansSC = loadLocalFont("NotoSansSC", "Noto Sans SC");
 *   // notoSansSC.fontFamily === "Noto Sans SC"
 *
 * Prerequisites:
 *   - Font woff2 files in public/fonts/<FontFamilyName>/*.woff2
 *   - font-manifest.json in project root (generated by setup-project.sh)
 */

import { staticFile } from "remotion";

/**
 * Load all woff2 files for a font family from public/fonts/<familyName>/.
 * Mirrors the return type of @remotion/google-fonts loadFont().
 */
export function loadLocalFont(
  /** Directory name under public/fonts/ (e.g. "NotoSansSC") */
  familyDir: string,
  /** CSS font-family name (e.g. "Noto Sans SC") */
  fontFamily: string,
  /** Files to load — each should be a .woff2 filename in the family dir */
  files: Array<{ filename: string; weight: string }>
): { fontFamily: string } {
  // On server-side (SSR / Remotion bundler), FontFace is not available
  if (typeof FontFace === "undefined") {
    return { fontFamily };
  }

  for (const file of files) {
    const url = staticFile(`fonts/${familyDir}/${file.filename}`);
    const fontFace = new FontFace(fontFamily, `url(${url})`, {
      weight: file.weight,
      style: "normal",
    });
    document.fonts.add(fontFace);
    // Fire-and-forget load (same as @remotion/google-fonts)
    fontFace.load().catch(() => {
      // Silent fail — font will fall back to system default
    });
  }

  return { fontFamily };
}
